[MUEmoji]
MUEmojiSwitch=0

[Version]
MainCode = 1.03.34
[FontConfig]
FontName 		= Tahoma
FontWeight 		= 1
FontHeight 		=13
FontAlias 		= 3
FpsWingMotion 	=0
Wide			= 0
WindowsSD		=0
[ACuoi]
;BODY_X1 = 0.0020
;BODY_Y1 = 0.1
;BODY_W1 = 0.1
;BODY_H = 0.1
