ACuoi_MEXE			= 0xA6415127
ACuoi_PBMD			= 0x7D56FCEB
;==============================================================
CustomModelNpc		= FOUND OK!
BuffEffect			= FOUND OK!
JCItemToolTip		= FOUND OK!
JCTextTooltip		= FOUND OK!
CustomClaws			= FOUND OK!
CustomPet			= FOUND OK!
CustomBowCross		= FOUND OK!
CustomMonsterGlow	= FOUND OK!
CustomMonster		= FOUND OK!
CustomItem			= FOUND OK!
CustomWing			= FOUND OK!
CustomNameNpc		= FOUND OK!
CustomJewel			= FOUND OK!
CustomEventTime		= FOUND OK!
;==============================================================
; Wednesday, 19:40:37 09/09/2026
;==============================================================
