[ThangCuoi]
;=================================================================================================================
;					FACEBOOK: https://www.facebook.com/mukynguyen/
;					Zalo + SĐT : BQT MU KỶ NGUYÊN
;					Name : MU KỶ NGUYÊN
;=======Cung Cấp Sever Mu Online========
;-Phiên Bản
;+DLL Clasic Cutsom Có Đủ
;+5.2 FPS 120 Siêu Mượt
;======Hỗ Trợ=========
;+Config Sever Theo Ý Muốn
;+Dịch Vụ VPS Hosting Tên Miền Antihack
;=================================================================================================================
CustomerName		= ThangCuoi
ClientSerial		= ACuoi-0968092399
ClientVersion 		= 1.03.34
;----------------------------------------------------------------------------
IpAddress 			= 127.0.0.2
IpAddressPort 		= 44405
WindowName 			= Mu Onnile
ClientName 			= Main.exe
ScreenShotPath		= Photoshop\Screen(%02d_%02d-%02d-%02d)-%04d.jpg
;----------------------------------------------------------------------------
;Max Cửa Sổ Game
MaxGameInstances 	= 5
;Thời Gian Kết Nối Lại Khi Disconnet Game-> Tính Bằng Giây Nên Để 30 Không Thay Đổi
ReconnectTime 		= 30
;Camera Mặc định cao nhất.
CameraDefault 		= 50
PluginName 			= iAnti.bmd
;----------------------------------------------------------------------------
;Sub Server
ServerName_1 = %s - Máy Chủ %d %s
ServerName_2 = %s - Máy Chủ %d [VIP] %s
ServerName_3 = %s - Máy Chủ %d [Non-PK] %s
ServerName_4 = %s - Máy Chủ %d %s
;----------------------------------------------------------------------------
;FPS Mặc Định
DefaultFPS = 120
;----------------------------------------------------------------------------
;Bật tắt Menu.
;----------------------------------------------------------------------------
MENU_BUTTON_01 = 1        //Bảng Xếp Hạng
MENU_BUTTON_02 = 1        //Bảng Sự Kiện
MENU_BUTTON_03 = 0        //Relife
MENU_BUTTON_04 = 1        //Đổi Reset
MENU_BUTTON_05 = 1        //Danh Hiệu
MENU_BUTTON_06 = 1        //Vòng Quay May Mắn
MENU_BUTTON_07 = 1        //Vip Tài Khoản
MENU_BUTTON_08 = 0        //Tích Lũy Mốc Nạp (tắt)
MENU_BUTTON_09 = 1        //Đổi Chủng Tộc
MENU_BUTTON_10 = 1        //Đổi Mật Khẩu 
MENU_BUTTON_11 = 1        //Hồn Hoàn
MENU_BUTTON_12 = 1        //Shop Game (XShop WcoinC / WcoinP)
MENU_BUTTON_13 = 1        //Quân Hàm
MENU_BUTTON_14 = 1        //Tu Luyện
MENU_BUTTON_15 = 1        //Giftcode Tân Thủ
;----------------------------------------------------------------------------
;Bật tắt 3 Nút ở bản C ( 0 tắt, 1 Bật )
ButtonCharracter 	= 1
;Bật tắt nút Treo shop tiền tệ ( 0 tắt, 1 bật )
ButtonShopWcoinC 	= 1
ButtonShopWcoinP 	= 1
ButtonShopWcoinG 	= 0
ButtonShopJwBless 	= 0
ButtonShopJwSoul 	= 0
ButtonShopChaos 	= 0
ButtonShopZens 		= 1
;=================================
;-- Sử dụng skill công thành chiến
;-- Bật/tắt tại GameServerInfo-Common.dat
;=================================
;1 = Tắt 0 = Bật
EnableCsSkillsAllMaps = 0