;Tên DataServerODBC / Phải Trùng  Với JoinServer 
;Khi Cài DB Lên SQL Xong Hãy Chạy Reg32.reg Và Reg64.reg
;Hỗ Trợ Cài Sever Onlinne Và Offnile
;Liên Hệ Ngay Zalo Hoặc SĐT : 0968092399 MU KỶ NGUYÊN
;SĐT Chính Chủ Từ Zalo FB
;Đúng SĐT Đúng Tên Đúng Người 
;Lừa Đảo Nhiều Anh Em Mua Bán Gì Nên Cẩn Thận ! Xin Cảm Ơn
[DataServerInfo]
DataServerODBC = MuThangCuoi
DataServerPort = 55960