;Không Nên Đổi Port Nếu Không Biết Đổi
;Thêm Port 
;-ConnectServerPortTCP Vào VPS Để Chạy Online
;Nếu Chạy OFF Thì Không Cần Thêm Bất Cứ Port Gì Tải SQL Cài DB Là Bú
;Hỗ Trợ Cài Sever Onlinne Và Offnile
;Liên Hệ Ngay Zalo Hoặc SĐT : 0968092399 MU KỶ NGUYÊN
;SĐT Chính Chủ Từ Zalo FB
;Đúng SĐT Đúng Tên Đúng Người 
;Lừa Đảo Nhiều Anh Em Mua Bán Gì Nên Cẩn Thận ! Xin Cảm Ơn
[ConnectServerInfo]
ConnectServerPortTCP = 44405
ConnectServerPortUDP = 55557
Version = Premium
MaxIpConnection = 10