;=================================================================================================================
;					FACEBOOK: https://www.facebook.com/mukynguyen/
;					Zalo + SĐT : BQT MU KỶ NGUYÊN
;					Name : MU KỶ NGUYÊN
;=======Cung Cấp Sever Mu Online========
;-Phiên Bản
;+DLL Clasic Cutsom Có Đủ
;+5.2 FPS 120 Siêu Mượt
;======Hỗ Trợ=========
;+Config Sever Theo Ý Muốn
;+Dịch Vụ VPS Hosting Tên Miền Antihack
;=================================================================================================================
[ServerInfo]
;==========================
CustomerName 	= ThangCuoi
ClientVersion 	= 1.03.34
ClientSerial 	= ACuoi-0968092399
AntihackPort 	= 55858
;==========================
;Giới hạn cửa sổ game theo máy tính 0 = không giới hạn
MaxGameInstances 	= 5
 ;Bật Reconnec Khi Tắt Antihack Không Bị Diss Game
ReconnectSwitch 	= 1
;Thời gian block khi phát hiện ddos (giây)
AntiFloodSwitch 	= 1
 ;Giới hạn cửa sổ game theo IP
MaxIpConnection 	= 5
;Thời gian khóa tạm thời khi phát hiện hack (giây)
DetectionLockTime 	= 10
;Thời gian phát hiện IP ddos ThoihhGianKhoaIPDos / 1000 = Số giây
ThoiGianKhoaIPDos 	= 30000              

;===========================
;-- Launcher
;===========================
LauncherName 		= 0
LauncherCRC 		= 0
;===========================
;-- EncDec Đồng bộ Key trong Data/Hack/MHPServer.ini
;===========================
EncDecKey1 			= 0
EncDecKey2 			= 0
EncDecSetNumber 	= 0
;===========================
;-- Setting
;===========================
VirtualMachineSwitch 	= 0
InternalVersion 		= 0
MemoryGuardSwitch 		= 0
MemoryGuardNumber 		= 0
MacroProtectSwitch 		= 0
MacroProtectNumber 		= 0
;===========================
;-- Memory (Can't be changed)
;===========================
;FTP: Tải lên ảnh chụp nhanh khi phát hiện bị hack
;===========================
[FTPInfo]
FTPSwitch = 0
IpAddress = 127.0.0.1
Port = 21
Username = Username
Password = Password
;===========================
;-- Discord (PREMIUM FEATURES)
;===========================
[Discord]
DiscordSwitch = 0
DiscordID = 0
HackLogSwitch = 0