;Tên JoinServerODBC / Phải Trùng  Với DataServer 
;Khi Cài DB Lên SQL Xong Hãy Chạy Reg32.reg Và Reg64.reg
;Hỗ Trợ Cài Sever Onlinne Và Offnile
;Liên Hệ Ngay Zalo Hoặc SĐT : 0968092399 MU KỶ NGUYÊN
;SĐT Chính Chủ Từ Zalo FB
;Đúng SĐT Đúng Tên Đúng Người 
;Lừa Đảo Nhiều Anh Em Mua Bán Gì Nên Cẩn Thận ! Xin Cảm Ơn
[JoinServerInfo]
JoinServerODBC = MuThangCuoi
JoinServerPort = 55970
ConnectServerAddress = 127.0.0.1
ConnectServerPort = 55557
CaseSensitive = 0
MD5Encryption = 0
SPKGLPW 	  = SpkDigital

;Bật tắt đăng ký trong game
;RegNewAccount 	||   1 Bật 0 tắt
;ChieuDaiKyTu 	||   Độ dài ký tự
;CharAccountReg	||   0: Đăng ký vừa chữ vừa số | 1: đăng ký mỗi số

RegNewAccount 			= 1    
ChieuDaiKyTu 			= 1	   
CharAccountReg			= 0    