export const CHARACTER_CLASS_OPTIONS = [
  { value: 0, label: "Dark Wizard (0)" },
  { value: 1, label: "Soul Master (1)" },
  { value: 2, label: "Grand Master (2)" },
  { value: 3, label: "Soul Wizard (3)" },
  { value: 16, label: "Dark Knight (16)" },
  { value: 17, label: "Blade Knight (17)" },
  { value: 18, label: "Blade Master (18)" },
  { value: 19, label: "Dragon Knight (19)" },
  { value: 32, label: "Fairy Elf (32)" },
  { value: 33, label: "Muse Elf (33)" },
  { value: 34, label: "High Elf (34)" },
  { value: 35, label: "Noble Elf (35)" },
  { value: 48, label: "Magic Gladiator (48)" },
  { value: 50, label: "Duel Master (50)" },
  { value: 51, label: "Magic Knight (51)" },
  { value: 64, label: "Dark Lord (64)" },
  { value: 66, label: "Lord Emperor (66)" },
  { value: 67, label: "Empire Lord (67)" },
  { value: 80, label: "Summoner (80)" },
  { value: 81, label: "Bloody Summoner (81)" },
  { value: 82, label: "Dimension Master (82)" },
  { value: 83, label: "Dimension Summoner (83)" },
  { value: 96, label: "Rage Fighter (96)" },
  { value: 98, label: "Fist Master (98)" },
  { value: 99, label: "Fist Blazer (99)" },
] as const;

export function className(cls: number) {
  const map: Record<number, string> = {
    0: "Phù Thủy",
    1: "Pháp Sư",
    2: "Đại Pháp Sư",
    3: "Soul Wizard",
    16: "Chiến Binh",
    17: "Kỵ Sĩ",
    18: "Blade Master",
    19: "Dragon Knight",
    32: "Tiên Nữ",
    33: "Thánh Nữ",
    34: "High Elf",
    35: "Noble Elf",
    48: "Đấu Sĩ",
    50: "Duel Master",
    51: "Magic Knight",
    64: "Chúa Tể",
    66: "Lord Emperor",
    67: "Empire Lord",
    80: "Summoner",
    81: "Bloody Summoner",
    82: "Dimension Master",
    83: "Dimension Summoner",
    96: "Rage Fighter",
    98: "Fist Master",
    99: "Fist Blazer",
  };
  return map[cls] ?? `Class ${cls}`;
}
